module.exports = {
  docs: {
    Docusaurus: ['doc1'],

    'API Reference': [
      {
        type: 'category',
        label: 'react-ocean-forms',
        items: [
          {
            type: 'category',
            label: 'Modules',
            items: [
              'api/react-ocean-forms/modules/fielderror',
              'api/react-ocean-forms/modules/fieldgroup',
              'api/react-ocean-forms/modules/fieldline',
              'api/react-ocean-forms/modules/form',
              'api/react-ocean-forms/modules/formbutton',
              'api/react-ocean-forms/modules/formcontext',
              'api/react-ocean-forms/modules/formtext',
              'api/react-ocean-forms/modules/input',
              'api/react-ocean-forms/modules/validationsummary',
              'api/react-ocean-forms/modules/common',
              'api/react-ocean-forms/modules/parsevalidationerror',
              'api/react-ocean-forms/modules/react',
              'api/react-ocean-forms/modules/stringformatter',
              'api/react-ocean-forms/modules/usefield',
              'api/react-ocean-forms/modules/useformcontext',
              'api/react-ocean-forms/modules/useformeventlistener',
              'api/react-ocean-forms/modules/useformtext',
              'api/react-ocean-forms/modules/usevalidation',
              'api/react-ocean-forms/modules/validators',
              'api/react-ocean-forms/modules/withfield',
              'api/react-ocean-forms/modules/withform',
            ],
          },
          {
            type: 'category',
            label: 'Interfaces',
            items: [
              'api/react-ocean-forms/interfaces/fielderror.ifielderrorprops',
              'api/react-ocean-forms/interfaces/fieldgroup.ifieldgroupprops',
              'api/react-ocean-forms/interfaces/fieldgroup.ifieldgrouprenderparams',
              'api/react-ocean-forms/interfaces/fieldgroup.iusefieldgroupargs',
              'api/react-ocean-forms/interfaces/fieldgroup.iusefieldgroupresult',
              'api/react-ocean-forms/interfaces/fieldline.ifieldlineprops',
              'api/react-ocean-forms/interfaces/form.iformprops',
              'api/react-ocean-forms/interfaces/formbutton.iformbuttonprops',
              'api/react-ocean-forms/interfaces/formcontext.ibaseformcontext',
              'api/react-ocean-forms/interfaces/formcontext.ifieldvalues',
              'api/react-ocean-forms/interfaces/formcontext.iformcontext',
              'api/react-ocean-forms/interfaces/formtext.iformtextprops',
              'api/react-ocean-forms/interfaces/input.iinputprops',
              'api/react-ocean-forms/interfaces/validationsummary.ivalidationsummaryprops',
              'api/react-ocean-forms/interfaces/stringformatter.imessagevalues',
              'api/react-ocean-forms/interfaces/usefield.ibasefieldprops',
              'api/react-ocean-forms/interfaces/usefield.ifieldchangedevent',
              'api/react-ocean-forms/interfaces/usefield.ifieldcomponentfieldprops',
              'api/react-ocean-forms/interfaces/usefield.ifieldcomponentmeta',
              'api/react-ocean-forms/interfaces/usefield.iusefieldprops',
              'api/react-ocean-forms/interfaces/usefield.iusefieldresult',
              'api/react-ocean-forms/interfaces/usefield.iusefieldstate',
              'api/react-ocean-forms/interfaces/usefield.ivaluemeta',
              'api/react-ocean-forms/interfaces/usevalidation.ibasicvalidationstate',
              'api/react-ocean-forms/interfaces/usevalidation.iusevalidationargs',
              'api/react-ocean-forms/interfaces/usevalidation.iusevalidationresult',
              'api/react-ocean-forms/interfaces/usevalidation.ivalidationargs',
              'api/react-ocean-forms/interfaces/usevalidation.ivalidationstate',
              'api/react-ocean-forms/interfaces/validators.idefaultvalidator',
              'api/react-ocean-forms/interfaces/validators.ifielderrorobject',
              'api/react-ocean-forms/interfaces/withfield.ifieldcomponentprops',
              'api/react-ocean-forms/interfaces/withform.iformcontextprops',
              'api/react-ocean-forms/interfaces/fielderror.ifielderrorprops',
              'api/react-ocean-forms/interfaces/fieldgroup.ifieldgroupprops',
              'api/react-ocean-forms/interfaces/fieldgroup.ifieldgrouprenderparams',
              'api/react-ocean-forms/interfaces/fieldgroup.iusefieldgroupargs',
              'api/react-ocean-forms/interfaces/fieldgroup.iusefieldgroupresult',
              'api/react-ocean-forms/interfaces/fieldline.ifieldlineprops',
              'api/react-ocean-forms/interfaces/form.iformprops',
              'api/react-ocean-forms/interfaces/formbutton.iformbuttonprops',
              'api/react-ocean-forms/interfaces/formcontext.ibaseformcontext',
              'api/react-ocean-forms/interfaces/formcontext.ifieldvalues',
              'api/react-ocean-forms/interfaces/formcontext.iformcontext',
              'api/react-ocean-forms/interfaces/formtext.iformtextprops',
              'api/react-ocean-forms/interfaces/input.iinputprops',
              'api/react-ocean-forms/interfaces/validationsummary.ivalidationsummaryprops',
              'api/react-ocean-forms/interfaces/stringformatter.imessagevalues',
              'api/react-ocean-forms/interfaces/usefield.ibasefieldprops',
              'api/react-ocean-forms/interfaces/usefield.ifieldchangedevent',
              'api/react-ocean-forms/interfaces/usefield.ifieldcomponentfieldprops',
              'api/react-ocean-forms/interfaces/usefield.ifieldcomponentmeta',
              'api/react-ocean-forms/interfaces/usefield.iusefieldprops',
              'api/react-ocean-forms/interfaces/usefield.iusefieldresult',
              'api/react-ocean-forms/interfaces/usefield.iusefieldstate',
              'api/react-ocean-forms/interfaces/usefield.ivaluemeta',
              'api/react-ocean-forms/interfaces/usevalidation.ibasicvalidationstate',
              'api/react-ocean-forms/interfaces/usevalidation.iusevalidationargs',
              'api/react-ocean-forms/interfaces/usevalidation.iusevalidationresult',
              'api/react-ocean-forms/interfaces/usevalidation.ivalidationargs',
              'api/react-ocean-forms/interfaces/usevalidation.ivalidationstate',
              'api/react-ocean-forms/interfaces/validators.idefaultvalidator',
              'api/react-ocean-forms/interfaces/validators.ifielderrorobject',
              'api/react-ocean-forms/interfaces/withfield.ifieldcomponentprops',
              'api/react-ocean-forms/interfaces/withform.iformcontextprops',
            ],
          },
          {
            type: 'category',
            label: 'Enums',
            items: ['api/react-ocean-forms/enums/validators.fielderrormessageid'],
          },
        ],
      },

      {
        type: 'category',
        label: 'react-ocean-forms-react-intl',
        items: [
          {
            type: 'category',
            label: 'Modules',
            items: [
              'api/react-ocean-forms-react-intl/modules/_intlform_',
              'api/react-ocean-forms-react-intl/modules/_intlform_types_',
            ],
          },
          {
            type: 'category',
            label: 'Interfaces',
            items: [
              'api/react-ocean-forms-react-intl/interfaces/_intlform_types_.iintlformprops',
              'api/react-ocean-forms-react-intl/interfaces/_intlform_types_.iintlformprops',
            ],
          },
        ],
      },

      {
        type: 'category',
        label: 'react-ocean-forms-bootstrap',
        items: [
          {
            type: 'category',
            label: 'Modules',
            items: [
              'api/react-ocean-forms-bootstrap/modules/_components_check_check_',
              'api/react-ocean-forms-bootstrap/modules/_components_check_check_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_datepicker_datepicker_',
              'api/react-ocean-forms-bootstrap/modules/_components_datepicker_datepicker_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_datepicker_plaintextdatepicker_plaintextdatepicker_',
              'api/react-ocean-forms-bootstrap/modules/_components_datepicker_plaintextdatepicker_plaintextdatepicker_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_fielderror_fielderror_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_fielderror_fielderror_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_fieldline_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_fieldline_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_fieldlineaddon_fieldlineaddon_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_fieldlineaddon_fieldlineaddon_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_fieldrow_fieldrow_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_fieldrow_fieldrow_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_infoaddonbutton_infoaddonbutton_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_infoaddonbutton_infoaddonbutton_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_infoalert_infoalert_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_infoalert_infoalert_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_invalidalert_invalidalert_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_invalidalert_invalidalert_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_requiredmarker_requiredmarker_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_requiredmarker_requiredmarker_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_validatingspinner_validatingspinner_',
              'api/react-ocean-forms-bootstrap/modules/_components_fieldline_validatingspinner_validatingspinner_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_formbutton_formbutton_',
              'api/react-ocean-forms-bootstrap/modules/_components_formbutton_formbutton_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_input_input_',
              'api/react-ocean-forms-bootstrap/modules/_components_input_input_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_onofftogglebutton_onofftogglebutton_',
              'api/react-ocean-forms-bootstrap/modules/_components_onofftogglebutton_onofftogglebutton_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_onofftogglebutton_onofftogglebuttonchoice_onofftogglebuttonchoice_',
              'api/react-ocean-forms-bootstrap/modules/_components_onofftogglebutton_onofftogglebuttonchoice_onofftogglebuttonchoice_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_onofftogglebutton_plaintextonofftogglebutton_plaintextonofftogglebutton_',
              'api/react-ocean-forms-bootstrap/modules/_components_onofftogglebutton_plaintextonofftogglebutton_plaintextonofftogglebutton_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_select_creatableselect_creatableselect_',
              'api/react-ocean-forms-bootstrap/modules/_components_select_creatableselect_creatableselect_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_select_select_select_',
              'api/react-ocean-forms-bootstrap/modules/_components_select_select_select_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_select_selectbase_selectbase_',
              'api/react-ocean-forms-bootstrap/modules/_components_select_selectbase_selectbase_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_validationsummary_validationfielderror_validationfielderror_',
              'api/react-ocean-forms-bootstrap/modules/_components_validationsummary_validationfielderror_validationfielderror_types_',
              'api/react-ocean-forms-bootstrap/modules/_components_validationsummary_validationsummary_',
              'api/react-ocean-forms-bootstrap/modules/_components_validationsummary_validationsummary_types_',
              'api/react-ocean-forms-bootstrap/modules/_utils_registercustommessages_',
            ],
          },
          {
            type: 'category',
            label: 'Interfaces',
            items: [
              'api/react-ocean-forms-bootstrap/interfaces/_components_check_check_types_.icheckprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_datepicker_datepicker_types_.ibasedatepickerprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_datepicker_datepicker_types_.idatepickerprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_datepicker_plaintextdatepicker_plaintextdatepicker_types_.plaintextdatepickerprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_fielderror_fielderror_types_.ifielderrorprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_fieldline_types_.ibasefieldlineprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_fieldline_types_.ifieldlineprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_fieldline_types_.iinfoprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_fieldlineaddon_fieldlineaddon_types_.ifieldlineaddonprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_fieldrow_fieldrow_types_.ifieldrowprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_infoaddonbutton_infoaddonbutton_types_.iinfoaddonbuttonprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_infoalert_infoalert_types_.iinfoalertprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_invalidalert_invalidalert_types_.iinvalidalertprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_requiredmarker_requiredmarker_types_.irequiredmarkerprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_validatingspinner_validatingspinner_types_.ivalidatingspinnerprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_formbutton_formbutton_types_.iformbuttonprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_input_input_types_.iinputprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_onofftogglebutton_onofftogglebutton_types_.ionofftogglebuttonprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_onofftogglebutton_onofftogglebuttonchoice_onofftogglebuttonchoice_types_.onofftogglebuttonchoiceprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_onofftogglebutton_plaintextonofftogglebutton_plaintextonofftogglebutton_types_.plaintextonofftogglebuttonprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_select_creatableselect_creatableselect_types_.icreatableselectprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_select_select_select_types_.iselectprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_select_selectbase_selectbase_types_.iselectbaseprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_select_selectbase_selectbase_types_.iselectbasepropsbase',
              'api/react-ocean-forms-bootstrap/interfaces/_components_select_selectbase_selectbase_types_.iselectoption',
              'api/react-ocean-forms-bootstrap/interfaces/_components_validationsummary_validationfielderror_validationfielderror_types_.ivalidationfielderrorprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_validationsummary_validationsummary_types_.ivalidationsummaryprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_check_check_types_.icheckprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_datepicker_datepicker_types_.ibasedatepickerprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_datepicker_datepicker_types_.idatepickerprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_datepicker_plaintextdatepicker_plaintextdatepicker_types_.plaintextdatepickerprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_fielderror_fielderror_types_.ifielderrorprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_fieldline_types_.ibasefieldlineprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_fieldline_types_.ifieldlineprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_fieldline_types_.iinfoprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_fieldlineaddon_fieldlineaddon_types_.ifieldlineaddonprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_fieldrow_fieldrow_types_.ifieldrowprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_infoaddonbutton_infoaddonbutton_types_.iinfoaddonbuttonprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_infoalert_infoalert_types_.iinfoalertprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_invalidalert_invalidalert_types_.iinvalidalertprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_requiredmarker_requiredmarker_types_.irequiredmarkerprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_fieldline_validatingspinner_validatingspinner_types_.ivalidatingspinnerprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_formbutton_formbutton_types_.iformbuttonprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_input_input_types_.iinputprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_onofftogglebutton_onofftogglebutton_types_.ionofftogglebuttonprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_onofftogglebutton_onofftogglebuttonchoice_onofftogglebuttonchoice_types_.onofftogglebuttonchoiceprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_onofftogglebutton_plaintextonofftogglebutton_plaintextonofftogglebutton_types_.plaintextonofftogglebuttonprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_select_creatableselect_creatableselect_types_.icreatableselectprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_select_select_select_types_.iselectprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_select_selectbase_selectbase_types_.iselectbaseprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_select_selectbase_selectbase_types_.iselectbasepropsbase',
              'api/react-ocean-forms-bootstrap/interfaces/_components_select_selectbase_selectbase_types_.iselectoption',
              'api/react-ocean-forms-bootstrap/interfaces/_components_validationsummary_validationfielderror_validationfielderror_types_.ivalidationfielderrorprops',
              'api/react-ocean-forms-bootstrap/interfaces/_components_validationsummary_validationsummary_types_.ivalidationsummaryprops',
            ],
          },
        ],
      },
    ],
  },
};
