const fs = require('fs');
const path = require('path');

function getApiSidebarContent(moduleName) {
  const sidebarFileLocation = path.resolve(__dirname, 'api_sidebars/', `${moduleName}.json`);
  if (fs.existsSync(sidebarFileLocation)) {
    const sidebarContent = require(sidebarFileLocation);
    return sidebarContent;
  }

  return ['api_autogenerated'];
}

module.exports = {
  docs: {
    Docusaurus: ['doc1'],

    'API Reference': [
      {
        type: 'category',
        label: 'react-ocean-forms',
        items: getApiSidebarContent('react-ocean-forms'),
      },
      {
        type: 'category',
        label: 'react-ocean-forms-bootstrap',
        items: getApiSidebarContent('react-ocean-forms-bootstrap'),
      },
      {
        type: 'category',
        label: 'react-ocean-forms-react-intl',
        items: getApiSidebarContent('react-ocean-forms-react-intl'),
      },
    ],
  },
};
